import { mkdir, writeFile, copyFile } from 'node:fs/promises';
import { profile, projects, stack, additionalLiveProjects } from '../src/data.mjs';
import { translateText } from '../src/he.mjs';
export const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const github = `https://github.com/${profile.username}`;
const ext = 'target="_blank" rel="noopener noreferrer"';
const tags = items => `<div class="tags">${items.map(t => `<span>${escape(t)}</span>`).join('')}</div>`;
const sourceUrl = (p, file) => `${github}/${p.repo}/blob/main/${file}`;
const diagram = p => `<div class="flow">${p.architecture.map((step,i) => `${i ? '<span class="flow-arrow" aria-hidden="true">↓</span>' : ''}<span>${escape(step)}</span>`).join('')}</div>`;
const card = (p,i) => `<article class="project-card" data-categories="${p.filters.join(',')}">
  <button class="project-art art-${p.id}" data-project="${p.id}" aria-label="View ${escape(p.name)} details"><span class="art-caption">${escape(p.label)}</span><span class="art-index">0${i+1}</span>${diagram(p)}<span class="art-bottom">${escape(p.category)}<span>↗</span></span></button>
  <div class="card-body"><div class="project-meta">${escape(p.category)}<span>0${i+1}</span></div><h3><button data-project="${p.id}">${escape(p.name)} <span>↗</span></button></h3><p>${escape(p.description)}</p>${tags(p.technologies.slice(0,5))}<div class="card-links"><button data-project="${p.id}">View details <span>→</span></button><a href="${github}/${p.repo}" ${ext}>GitHub ↗</a>${p.demo ? `<a href="${escape(p.demo)}" ${ext}>Live demo ↗</a>`:''}</div></div></article>`;
const live = [...projects.filter(p => p.demo), ...additionalLiveProjects];
const social = `<a href="${github}" ${ext}>GitHub ↗</a>${profile.linkedin ? `<a href="${escape(profile.linkedin)}" ${ext}>LinkedIn ↗</a>` : ''}<a href="mailto:${profile.email}">Email ↗</a><a href="tel:${profile.phoneHref}" aria-label="${profile.phone}"><bdi dir="ltr">${profile.phone}</bdi></a>`;
const html = `<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#0c100e"><title>Shulamit Katzenbogen | Full Stack & AI Developer</title><meta name="description" content="Shulamit Katzenbogen — Full Stack & AI Developer. Explore real projects in generative AI, RAG, backend engineering and automation."><meta property="og:type" content="website"><meta property="og:title" content="Shulamit Katzenbogen | Full Stack & AI Developer"><meta property="og:description" content="Building intelligent software with code, AI & automation. Explore selected engineering projects."><meta property="og:url" content="${profile.site}/"><meta property="og:image" content="${profile.site}/social-card.svg"><meta name="twitter:card" content="summary"><link rel="canonical" href="${profile.site}/"><link rel="icon" href="./favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="./styles.css"><script src="./app.js" defer></script></head>
<body><a class="skip" href="#main">Skip to content</a>
<header class="header"><div class="nav-wrap"><a class="brand" href="#home" aria-label="Shulamit Katzenbogen home">sk<span>.</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation" aria-label="Open navigation"><span></span><span></span></button><nav id="navigation" aria-label="Main navigation"><a href="#home" class="active">Home</a><a href="#about">About</a><a href="#stack">Tech stack</a><a href="#projects">Projects</a><a href="#achievements">Achievements</a><a href="#contact">Contact</a></nav><a class="nav-contact" href="mailto:${profile.email}">Let’s talk <span>↗</span></a></div></header>
<main id="main"><section id="home" class="hero container"><div class="hero-copy"><div class="eyebrow"><span class="status-dot"></span> FULL STACK & AI DEVELOPER</div><p class="hero-name">SHULAMIT KATZENBOGEN</p><h1>Building<br>intelligent<br><span>software.</span></h1><p class="hero-description">Bringing ideas to life with code, AI & automation.<br>From thoughtful interfaces to the systems behind them.</p><div class="hero-actions"><a class="button primary" href="#projects">View projects <span>↗</span></a><a class="button secondary" href="${github}" ${ext}>GitHub <span>↗</span></a><a class="text-link" href="#contact">Contact me →</a></div><div class="hero-social">${social}</div></div>
<div class="system-art" aria-label="Software engineering illustration: interface, application, intelligence and data layers"><div class="art-grid"></div><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="system-top"><span class="status-dot"></span> FROM IDEA TO SYSTEM <span>01 / 04</span></div><div class="layer layer-one"><span class="layer-icon">▣</span><div><small>01 / EXPERIENCE</small><strong>Thoughtful interfaces</strong><p>React · TypeScript</p></div><span class="layer-mark">↗</span></div><div class="layer layer-two"><span class="layer-icon">⇄</span><div><small>02 / ENGINEERING</small><strong>Connected systems</strong><p>APIs · Backend · Cloud</p></div><span class="layer-mark">↗</span></div><div class="layer layer-three"><span class="layer-icon">✳</span><div><small>03 / INTELLIGENCE</small><strong>AI with context</strong><p>LLMs · RAG · Agents</p></div><span class="layer-mark">↗</span></div><div class="system-bottom"><span>code. connect. create.</span><span class="art-spark">✳</span></div></div>
<div class="hero-footer"><span>SOFTWARE ENGINEERING, WITH INTELLIGENCE.</span><a href="#projects">Explore the work <span>↓</span></a></div></section>
<div class="expertise-strip"><div class="container"><span>FULL STACK DEVELOPMENT</span><b>✳</b><span>GENERATIVE AI</span><b>✳</b><span>BACKEND SYSTEMS</span><b>✳</b><span>AUTOMATION</span></div></div>
<section id="projects" class="section container"><div class="section-heading"><div><div class="eyebrow">01 / SELECTED WORK</div><h2>Ideas, engineered.</h2></div><p>A selection of systems I’ve built.<br>Explore the thinking. Dive into the code.</p></div><div class="project-toolbar"><div class="filters" role="group" aria-label="Filter projects">${['All projects','AI','Full Stack','Automation'].map((f,i) => `<button data-filter="${i ? f : 'all'}" aria-pressed="${!i}">${f}${!i ? ' <span>' + String(projects.length).padStart(2, '0') + '</span>' : ''}</button>`).join('')}</div><span class="project-count" aria-live="polite">${projects.length} projects</span></div><div class="project-grid">${projects.map(card).join('')}</div></section>
${live.length ? `<section id="live" class="section container"><div class="eyebrow">LIVE PROJECTS</div><h2>Experience the work.</h2><div class="project-grid">${live.map(p=>`<article class="live-card">${diagram(p)}<h3>${escape(p.name)}</h3><p>${escape(p.description)}</p>${tags(p.technologies)}<a class="button primary" href="${escape(p.demo)}" ${ext}>Open live demo →</a></article>`).join('')}</div></section>` : ''}
<section id="about" class="section about-section"><div class="container about-grid"><div><div class="eyebrow">02 / BEHIND THE CODE</div><h2>Curious by nature.<br><span>Builder by mindset.</span></h2><div class="about-signature">Shulamit Katzenbogen <span>↗</span></div></div><div class="about-copy"><p class="lead">I’m a Full Stack & AI Developer who enjoys connecting thoughtful software engineering with the possibilities of AI.</p><p>My work spans frontend applications, backend services and generative AI systems — from routing knowledge through RAG pipelines to connecting vision and reasoning agents in an insurance workflow.</p><p>I care about how the pieces fit together: clear APIs, purposeful data models and automation that solves a practical problem.</p><a class="text-link" href="${github}" ${ext}>Get to know my work on GitHub ↗</a></div></div></section>
<section id="stack" class="section container"><div class="section-heading"><div><div class="eyebrow">03 / THE TOOLKIT</div><h2>The right tools.<br>Real applications.</h2></div><p>Technologies behind the projects.<br>Select a tool to see it in context.</p></div><div class="stack-grid">${stack.map(s=>`<article class="stack-card"><span class="stack-icon">${s.icon}</span><h3>${s.name}</h3><div class="stack-items">${s.items.map(([name,id])=>`<button data-project="${id}">${escape(name)} <span>↗</span></button>`).join('')}</div></article>`).join('')}</div></section>
<section id="achievements" class="section container"><div class="eyebrow">04 / A MOMENT THAT MATTERS</div><div class="achievement"><div class="award-icon" aria-hidden="true">✳</div><div><span class="award-label">DIRECT INSURANCE HACKATHON</span><h2>Built under pressure.<br>Recognized for impact.</h2><p>Hackathon winner for developing a complex, real-time AI platform for Direct Insurance.</p><button class="text-link" data-project="directvision">Explore DirectVision →</button></div><div class="winner-stamp"><span>HACKATHON</span><strong>Winner</strong><span>CODE × AI × TEAMWORK</span></div></div></section>
<section class="github-section container" aria-label="GitHub profile"><div><div class="eyebrow">OPEN CODE. REAL WORK.</div><h2>More behind the scenes.</h2><p>@${profile.username}</p><a class="text-link" href="${github}" ${ext}>View GitHub profile ↗</a></div><div class="github-stats"><strong>${profile.repositories}<span>public repositories</span></strong><div><span>Python · TypeScript · C#</span><small>Also Java, JavaScript & Dart<br>Public repository snapshot · ${profile.reviewed}</small></div></div></section>
<section id="contact" class="section container contact"><div class="eyebrow"><span class="status-dot"></span> LET’S CONNECT</div><h2>Let’s build<br>something <span>great.</span></h2><p>Looking for a developer who connects full stack engineering with AI?<br>I’d love to hear about your team and what you’re building.</p><a class="button primary" href="mailto:${profile.email}">Email me <span>↗</span></a><a class="email-address" href="mailto:${profile.email}">${profile.email}</a><div class="contact-social">${social}</div></section></main>
<footer class="container footer"><a class="brand" href="#home">sk<span>.</span></a><span>© ${new Date().getFullYear()} Shulamit Katzenbogen</span><a href="#home">Back to top ↑</a></footer>
${projects.map(p=>`<dialog id="dialog-${p.id}" aria-labelledby="title-${p.id}"><div class="dialog-top"><span class="eyebrow">PROJECT NOTES / ${escape(p.category)}</span><button class="dialog-close" aria-label="Close project details" autofocus>✕</button></div><h2 id="title-${p.id}">${escape(p.name)}</h2>${tags(p.technologies)}<div class="detail-section"><h3>Overview</h3><p>${escape(p.overview)}</p></div><div class="detail-columns"><div><h3>Problem</h3><p>${escape(p.problem)}</p></div><div><h3>Solution</h3><p>${escape(p.solution)}</p></div></div><div class="detail-section"><h3>Key features</h3><ul>${p.features.map(f=>`<li>${escape(f)}</li>`).join('')}</ul></div><div class="detail-section"><h3>Architecture</h3>${diagram(p)}<p class="detail-note">${escape(p.architectureNote)}</p></div><details><summary>Explore the source</summary><ul>${p.sources.map(file=>`<li><a href="${sourceUrl(p,file)}" ${ext}>${escape(file)} ↗</a></li>`).join('')}</ul></details><a class="button primary" href="${github}/${p.repo}" ${ext}>View repository ↗</a></dialog>`).join('')}
<aside class="language-widget" aria-label="Website language"><button class="language-toggle" aria-expanded="false" aria-controls="language-panel"><span aria-hidden="true">◎</span> Language / שפה</button><div id="language-panel" hidden><div class="language-heading"><strong>Website language</strong><button class="language-close" aria-label="Close language settings">✕</button></div><p>Choose your preferred language.</p><div class="language-options"><a href="./index.html" data-language="en" lang="en" dir="ltr" aria-current="true">English</a><a href="./he.html" data-language="he" lang="he" dir="rtl">עברית</a></div></div></aside>
</body></html>`;
const alternates = `<link rel="alternate" hreflang="en" href="${profile.site}/"><link rel="alternate" hreflang="he" href="${profile.site}/he.html">`;
const englishHtml = html.replace('</head>', `<link rel="stylesheet" href="./language.css">${alternates}</head>`);
const decode = text => text.replace(/&amp;|&lt;|&gt;|&quot;|&#39;/g, entity => ({'&amp;':'&','&lt;':'<','&gt;':'>','&quot;':'"','&#39;':"'"}[entity]));
const hebrewHtml = englishHtml
  .replace(/>([^<]+)</g, (_, text) => `>${escape(translateText(decode(text)))}<`)
  .replace(/aria-label="([^"]+)"/g, (_, label) => `aria-label="${escape(translateText(decode(label)))}"`)
  .replace('<html lang="en">', '<html lang="he" dir="rtl">')
  .replace(`rel="canonical" href="${profile.site}/"`, `rel="canonical" href="${profile.site}/he.html"`)
  .replace(`property="og:url" content="${profile.site}/"`, `property="og:url" content="${profile.site}/he.html"`)
  .replace('data-language="en" lang="en" dir="ltr" aria-current="true"', 'data-language="en" lang="en" dir="ltr"')
  .replace('data-language="he" lang="he" dir="rtl"', 'data-language="he" lang="he" dir="rtl" aria-current="true"')
  .replace('content="Shulamit Katzenbogen | Full Stack & AI Developer"', 'content="שולמית קצנבוגן | מפתחת Full Stack ו־AI"')
  .replace('content="Shulamit Katzenbogen — Full Stack & AI Developer. Explore real projects in generative AI, RAG, backend engineering and automation."', 'content="שולמית קצנבוגן — מפתחת Full Stack ו־AI. פרויקטים בבינה מלאכותית יוצרת, RAG, פיתוח צד שרת ואוטומציה."')
  .replace('content="Building intelligent software with code, AI & automation. Explore selected engineering projects."', 'content="בונה תוכנה חכמה עם קוד, AI ואוטומציה. מוזמנים להכיר פרויקטים נבחרים."');
await mkdir('dist', {recursive:true});
await writeFile('dist/index.html', englishHtml);
await writeFile('dist/he.html', hebrewHtml);
for (const file of ['styles.css','language.css','app.js','favicon.svg','social-card.svg']) await copyFile(`public/${file}`, `dist/${file}`);
await writeFile('dist/.nojekyll', '');
await writeFile('dist/robots.txt', `User-agent: *\nAllow: /\nSitemap: ${profile.site}/sitemap.xml\n`);
await writeFile('dist/sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${profile.site}/</loc></url><url><loc>${profile.site}/he.html</loc></url></urlset>`);
console.log(`Built ${projects.length} projects into dist/`);
